(()=>{
const PIXEL='DAN591JC77U5PB5VV4I0', TOTAL=15;
const qs=new URLSearchParams(location.search), savedArm=localStorage.getItem('epoch_arm'), savedPrice=localStorage.getItem('epoch_price_cell');
const state={step:1,arm:qs.get('arm')||savedArm||(Math.random()<.7?'paywall':'free'),price:qs.get('price_cell')||savedPrice||(Math.random()<.5?'14.99':'19.99'),answers:{},seen:new Set(),session:crypto.randomUUID?.()||String(Date.now()),email:'',timer:600};
localStorage.setItem('epoch_arm',state.arm);localStorage.setItem('epoch_price_cell',state.price);
const utm={};['utm_source','utm_medium','utm_campaign','utm_content','utm_term','ttclid'].forEach(k=>{const v=qs.get(k);if(v)localStorage.setItem('epoch_'+k,v);utm[k]=v||localStorage.getItem('epoch_'+k)||''});
const app=document.getElementById('app');
const art=n=>`assets/screens/screen-${String(n).padStart(2,'0')}.jpg`;
const data={
2:{key:'hook',title:'What makes you need to know what happens next?',multi:false,opts:[['decision','A decision that changes everything',null,'You want the moment history turns.'],['trapped','People trapped with no clean way out',null,'You stay for pressure with no easy exit.'],['secret','A secret that cannot stay buried',null,'You want the truth behind the headline.'],['love','A relationship history will not allow',null,'You connect when history becomes personal.']]},
3:{key:'stakes',title:'Which stakes pull you in fastest?',opts:[['nation','A nation on the edge',null,'Large events land through immediate consequences.'],['life','One life in immediate danger',null,'You feel history at human scale.'],['mission','A mission that could collapse',null,'You want plans under impossible pressure.'],['family','A family caught inside a larger crisis',null,'You follow the private cost of public events.']]},
4:{key:'engine',title:'Which kind of true story sounds best tonight?',opts:[['espionage','Espionage and hidden operations',null,'You want the machinery hidden behind events.'],['revolution','Revolutions, coups and power shifts',null,'You watch power move before the world catches up.'],['hostage','Hostage crises and impossible negotiations',null,'You want pressure measured in choices.'],['survival','Expeditions, disasters and survival',null,'You stay when endurance becomes the story.'],['scandal','Scandals, cover-ups and betrayal',null,'You want the truth someone tried to bury.']]},
5:{key:'opening',title:'How should the story begin?',opts:[['crisis','Drop me into the crisis immediately',null,'No warm-up. You want the fuse already lit.'],['calm','Start with calm, then tighten the pressure',null,'You like dread that earns its way in.'],['mystery','Open with a mystery I have to solve',null,'You want questions before answers.'],['outcome','Show the outcome, then reveal how it happened',null,'You like consequences first, causes second.']]},
6:{key:'context',title:'How much history do you want before the drama takes over?',opts:[['none','Almost none - let the story teach me',null,'The story should carry the history.'],['enough','Just enough to understand the stakes',null,'Context should serve the tension.'],['setup','A clear setup before the action',null,'You want solid ground before it moves.'],['expert','I already know the history - surprise me',null,'The familiar needs a new angle.']]},
7:{key:'viewpoint',title:'Whose view gets you closest to the story?',opts:[['decision','The person making the impossible decision',null,'You want history from inside responsibility.'],['trapped','The person trapped by that decision',null,'You want history from inside its consequences.'],['operative','The operative trying to control events',null,'You want the hand behind the move.'],['witness','The witness who sees what others miss',null,'You want the detail everyone else overlooks.']]},
8:{key:'tone',title:'What should the premiere feel like?',opts:[['tense','Tense and claustrophobic',null,'You want the walls closing in.'],['epic','Epic and consequential',null,'You want consequences large enough to echo.'],['intimate','Intimate and emotional',null,'You want the event to stay human.'],['investigative','Investigative and unsettling',null,'You want certainty to keep slipping.']]},
9:{key:'length',title:'What pace fits you best?',opts:[['short','3-5 minutes, all momentum',null,'Every scene should earn the next one.'],['medium','6-8 minutes, room for twists',null,'You want pace with room to turn.'],['long','9-12 minutes, deeper immersion',null,'You want the world to close around you.'],['surprise','Surprise me if the story earns it',null,'The story decides the clock.']]},
10:{key:'eras',title:'Where should EPOCH search first?',multi:true,max:3,opts:[['ancient','Ancient and medieval worlds',null,''],['empires','Empires and revolutions',null,''],['wars','The world wars',null,''],['coldwar','Cold War and espionage',null,''],['recent','Recent history',null,''],['anywhere','Anywhere - surprise me',null,'']]},
11:{key:'aftertaste',title:'What should stay with you after an episode?',opts:[['shock','“I can’t believe that happened.”',null,'You want history to land as a shock.'],['empathy','“I understand why they did it.”',null,'You want judgment complicated by understanding.'],['argument','“I need to argue about that choice.”',null,'You want consequences, not easy closure.'],['next','“I have to watch the next episode.”',null,'You want the last beat to open a door.']]},
12:{key:'familiarity',title:'How familiar should your first story be?',opts:[['known','A headline I know, told differently',null,'A new angle on familiar history.'],['barely','Something I have barely heard of',null,'Recognition without predictability.'],['unexpected','Completely unexpected',null,'The archive stays wide open.']]}
};
function payload(extra={}){return{session_id:state.session,arm:state.arm,price_cell:state.price,step:state.step,...utm,...extra}}
function track(name,extra={}){const p=payload(extra);window.dataLayer=window.dataLayer||[];dataLayer.push({event:name,...p});if(window.ttq?.track)ttq.track(name,p);console.info('[epoch-event]',name,p)}
function stepView(){const k=`EPOCHQuizStep${String(state.step).padStart(2,'0')}View`;if(!state.seen.has(k)){state.seen.add(k);track(k)}}
function shell(body){const pct=Math.round((state.step-1)/(TOTAL-1)*100);app.innerHTML=`<section class="screen"><header><button id="back" ${state.step===1?'disabled':''}>←</button><span class="brand">EPOCH</span><span>${state.step}/${TOTAL}</span></header><div class="progress"><i style="width:${pct}%"></i></div>${body}</section>`;document.getElementById('back').onclick=()=>{if(state.step>1){state.step--;render()}};stepView()}
function selectQ(step,value){const q=data[step];if(q.multi){let a=state.answers[q.key]||[];a=a.includes(value)?a.filter(x=>x!==value):a.length<q.max?[...a,value]:a;state.answers[q.key]=a;render();return}state.answers[q.key]=value;const o=q.opts.find(x=>x[0]===value);const fb=document.querySelector('.feedback');if(fb)fb.textContent=o[3];track('EPOCHQuestionAnswer',{question:q.key,answer:value});setTimeout(()=>{state.step++;render()},520)}
function question(){const q=data[state.step],chosen=state.answers[q.key]||[];shell(`<div class="content"><p class="eyebrow">YOUR EPOCH PREMIERE</p><h1>${q.title}</h1><div class="screen-visual" style="background-image:linear-gradient(0deg,rgba(5,5,6,.72),rgba(5,5,6,.04)),url('${art(state.step)}')"></div>${q.multi?'<p class="sub">Choose up to 3.</p>':''}<div class="options ${q.opts.some(x=>x[2])?'visual-options':''}">${q.opts.map(o=>`<button class="option ${(q.multi?chosen.includes(o[0]):chosen===o[0])?'chosen':''}" data-v="${o[0]}" ${o[2]?`style="--bg:url('${o[2]}')"`:''}><span>${o[1]}</span></button>`).join('')}</div><p class="feedback">${q.multi&&chosen.length?`${chosen.length} selected. Continue when ready.`:' '}</p>${q.multi?'<button class="primary" id="continue" '+(!chosen.length?'disabled':'')+'>Continue</button>':''}</div>`);document.querySelectorAll('.option').forEach(b=>b.onclick=()=>selectQ(state.step,b.dataset.v));if(q.multi)document.getElementById('continue').onclick=()=>{track('EPOCHQuestionAnswer',{question:q.key,answer:chosen.join(',')});state.step++;render()}}
function profile(){const hook=state.answers.hook||'pressure',tone=state.answers.tone||'tense';return `${hook[0].toUpperCase()+hook.slice(1)} ${tone[0].toUpperCase()+tone.slice(1)} Viewer`}
function render(){if(state.step===1)return shell(`<div class="hero"><div><p class="eyebrow">PERSONALIZED CINEMATIC HISTORY</p><h1>Find the true stories you won’t stop watching.</h1><p>Tell us what grips you. We’ll build your premiere.</p><button class="primary" id="start">Build my premiere</button><small>About 2 minutes · No payment</small></div></div>`),document.getElementById('start').onclick=()=>{track('EPOCHQuizStart');state.step=2;render()};
if(state.step>=2&&state.step<=11)return question();
if(state.step===12)return shell(`<div class="content analysis"><p class="eyebrow">BUILDING YOUR PREMIERE</p><h1>${data[12].title}</h1><div class="screen-visual" style="background-image:linear-gradient(0deg,rgba(5,5,6,.72),rgba(5,5,6,.04)),url('${art(12)}')"></div><div class="analysis-bars"><span>Matching your tension profile</span><i></i><span>Balancing context and pace</span><i></i><span>Ranking story worlds</span><i></i></div><div class="options">${data[12].opts.map(o=>`<button class="option" data-v="${o[0]}"><span>${o[1]}</span></button>`).join('')}</div><div class="chips"><b>${profile()}</b><b>${state.answers.engine||'Story-first'}</b><b>${state.answers.opening||'Fast reveal'}</b></div></div>`),document.querySelectorAll('.option').forEach(b=>b.onclick=()=>selectQ(12,b.dataset.v));
if(state.step===13)return shell(`<div class="content email"><p class="eyebrow">YOUR PREMIERE IS READY</p><h1>Save your profile.</h1><div class="screen-visual" style="background-image:linear-gradient(0deg,rgba(5,5,6,.72),rgba(5,5,6,.04)),url('${art(13)}')"></div><p class="sub">Enter your email to reveal your recommendation and get launch access.</p><form id="lead"><label>Email<input type="email" name="email" required autocomplete="email" placeholder="you@example.com"></label><button class="primary">Reveal my premiere</button></form><small>No payment now. We’ll email you before launch.</small></div>`),document.getElementById('lead').onsubmit=submitLead;
if(state.step===14)return summary();
return destination()}
function submitLead(e){e.preventDefault();state.email=e.target.email.value;const body=new URLSearchParams({"form-name":"epoch-quiz-leads",email:state.email,arm:state.arm,price:state.arm==='paywall'?state.price:'',profile:JSON.stringify(state.answers)});track('SubmitForm');track('Lead');fetch('/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body}).finally(()=>{state.step=14;render()})}
function summary(){const anchor=state.price==='14.99'?'19.99':'24.99';shell(`<div class="content summary"><p class="eyebrow">YOUR EPOCH PROFILE</p><h1>${profile()}</h1><p class="sub">You want human-scale pressure, clean context and consequences that keep opening doors.</p><div class="episode-cards"><article><div class="summary-visual" style="background-image:linear-gradient(0deg,rgba(5,5,6,.65),rgba(5,5,6,.05)),url('${art(14)}')"></div><b>EPISODE 1</b><h2>The Gate</h2><p>A diplomatic crisis closes in.</p><em>Ready to watch</em></article><article class="soon"><b>EPISODE 2</b><h2>444 Days</h2><p>The standoff changes everyone.</p><em>Coming soon</em></article><article class="soon"><b>EPISODE 3</b><h2>After the Headlines</h2><p>The consequences keep moving.</p><em>Coming soon</em></article></div>${state.arm==='paywall'?`<div class="offer"><p class="eyebrow">FOUNDING ACCESS</p><div class="price"><s>$${anchor}</s><strong>$${state.price}</strong><span>/month</span></div><ul><li>Episode 1 premiere</li><li>Founding price reserved</li><li>Email before any charge</li></ul><p>Price held for this session: <b id="timer">10:00</b></p><button class="primary" id="offerCta">Reserve my founding price</button><small>No charge today.</small></div>`:`<button class="primary" id="offerCta">Start episode 1</button>`}</div>`);track('EPOCHRecommendationView');if(state.arm==='paywall'){track('InitiateCheckout',{currency:'USD',value:+state.price});track('PriceCellView',{currency:'USD',value:+state.price});tick()}document.getElementById('offerCta').onclick=()=>{if(state.arm==='paywall')track('EPOCHFoundingPriceReserved',{currency:'USD',value:+state.price});state.step=15;render()}}
function tick(){const el=document.getElementById('timer');if(!el)return;el.textContent=`${Math.floor(state.timer/60)}:${String(state.timer%60).padStart(2,'0')}`;if(state.timer-->0)setTimeout(tick,1000)}
function destination(){shell(`<div class="content player"><p class="eyebrow">${state.arm==='paywall'?'FOUNDING PRICE SAVED':'YOUR PREMIERE'}</p><h1>Episode 1: The Gate</h1><div class="video" style="background-image:linear-gradient(#0005,#0009),url('${art(15)}')"><div><b>EPISODE 1</b><span>Final approved episode video will be placed here.</span></div></div><button class="primary" id="complete">Complete episode 1</button><div class="coming"><article>Episode 2 <b>Coming soon</b></article><article>Episode 3 <b>Coming soon</b></article></div></div>`);document.getElementById('complete').onclick=()=>{track('series_complete',{available_episodes:1});app.querySelector('.content').innerHTML='<div class="done"><p class="eyebrow">PREMIERE COMPLETE</p><h1>Your next stories are coming soon.</h1><p>We’ll email you when the next episode is ready.</p></div>'}}
render();
})();
