(()=>{
const PIXEL='DAN591JC77U5PB5VV4I0', TOTAL=15;
const qs=new URLSearchParams(location.search), savedArm=localStorage.getItem('epoch_arm'), savedPrice=localStorage.getItem('epoch_price_cell');
const state={step:1,arm:qs.get('arm')||savedArm||(Math.random()<.7?'paywall':'free'),price:qs.get('price_cell')||savedPrice||(Math.random()<.5?'14.99':'19.99'),answers:{},seen:new Set(),session:crypto.randomUUID?.()||String(Date.now()),email:'',timer:600,processingStarted:false};
localStorage.setItem('epoch_arm',state.arm);localStorage.setItem('epoch_price_cell',state.price);
const utm={};['utm_source','utm_medium','utm_campaign','utm_content','utm_term','ttclid'].forEach(k=>{const v=qs.get(k);if(v)localStorage.setItem('epoch_'+k,v);utm[k]=v||localStorage.getItem('epoch_'+k)||''});
const app=document.getElementById('app');
const art=n=>`assets/screens/screen-${String(n).padStart(2,'0')}.jpg`;
const data={
2:{key:'hook',title:'What keeps you watching a true story?',opts:[['turning_point','A decision that changes everything','A turning point pulls you in.'],['danger','Someone facing real danger','You connect when the stakes are immediate.'],['secret','A hidden truth coming to light','You want to uncover what really happened.'],['relationship','A personal relationship under pressure','People make history matter to you.']]},
3:{key:'stakes',title:'Which scale of story interests you most?',opts:[['world','Countries and world events','You want the big picture.'],['mission','A mission that could fail','You like a clear goal under pressure.'],['person','One person in danger','You connect with history at human scale.'],['family','A family inside a crisis','You care about the private cost of public events.']]},
4:{key:'engine',title:'Which true stories would you watch first?',opts:[['espionage','Spies and secret operations','Hidden operations are your strongest match.'],['power','Revolutions, coups and power shifts','You want to see how power changes hands.'],['crisis','Hostage crises and negotiations','You like impossible choices under pressure.'],['survival','Disasters, expeditions and survival','You want stories of endurance.'],['scandal','Scandals, cover-ups and betrayal','You want the truth someone tried to hide.']]},
5:{key:'motivation',title:'Why do you want to learn more history?',opts:[['world','To understand why the world works as it does','You want history to explain the present.'],['smarter','To become more knowledgeable','You want useful knowledge that stays with you.'],['people','To understand people and their decisions','Human choices are your way into history.'],['conversation','To have better conversations','You want stories worth sharing and discussing.'],['entertainment','To be entertained while learning','The experience has to earn your attention.']]},
6:{key:'age_group',title:'What is your age group?',opts:[['18_24','18–24','Thanks — this helps us tailor the experience.'],['25_34','25–34','Thanks — this helps us tailor the experience.'],['35_44','35–44','Thanks — this helps us tailor the experience.'],['45_54','45–54','Thanks — this helps us tailor the experience.'],['55_plus','55+','Thanks — this helps us tailor the experience.'],['prefer_not','Prefer not to say','No problem — we can still personalize your premiere.']]},
7:{key:'daily_time',title:'How much time would you spend learning history on a typical day?',opts:[['under_5','Less than 5 minutes','We’ll keep your stories short and focused.'],['5_10','5–10 minutes','Short daily episodes fit you well.'],['10_20','10–20 minutes','You have room for a complete story arc.'],['20_plus','More than 20 minutes','You’re open to deeper sessions.'],['depends','It depends on the story','The story has to earn your time.']]},
8:{key:'tone',title:'What mood do you prefer?',opts:[['tense','Tense and suspenseful','You want to feel the pressure.'],['epic','Big and dramatic','You want history to feel consequential.'],['emotional','Personal and emotional','You want the human story first.'],['investigative','Investigative and surprising','You want evidence, reveals and new angles.']]},
9:{key:'episode_length',title:'How long should one episode be?',opts:[['3_5','3–5 minutes','Fast, focused episodes fit your time.'],['6_8','6–8 minutes','You want pace with room for a twist.'],['9_12','9–12 minutes','You’re open to deeper immersion.'],['no_preference','No preference if the story is good','The story can decide the length.']]},
10:{key:'eras',title:'Which periods interest you?',multi:true,max:3,opts:[['ancient','Ancient & medieval'],['empires','Empires & revolutions'],['wars','World Wars'],['coldwar','Cold War & spies'],['recent','Recent history'],['anywhere','Surprise me']]},
11:{key:'aftertaste',title:'What should you feel after an episode?',opts:[['surprised','“I can’t believe that happened.”','You want history to surprise you.'],['understand','“Now I understand why they did it.”','You want decisions to make sense.'],['debate','“I need to discuss that choice.”','You want questions that stay with you.'],['next','“I have to watch the next episode.”','You want every ending to open another door.']]}
};
function payload(extra={}){return{session_id:state.session,arm:state.arm,price_cell:state.price,step:state.step,...utm,...extra}}
function track(name,extra={}){const p=payload(extra);window.dataLayer=window.dataLayer||[];dataLayer.push({event:name,...p});if(window.ttq?.track)ttq.track(name,p);console.info('[epoch-event]',name,p)}
function stepView(){const k=`EPOCHQuizStep${String(state.step).padStart(2,'0')}View`;if(!state.seen.has(k)){state.seen.add(k);track(k)}}
function shell(body){const pct=Math.round((state.step-1)/(TOTAL-1)*100);app.innerHTML=`<section class="screen"><header><button id="back" ${state.step===1?'disabled':''}>←</button><span class="brand">EPOCH</span><span>${state.step}/${TOTAL}</span></header><div class="progress"><i style="width:${pct}%"></i></div>${body}</section>`;document.getElementById('back').onclick=()=>{if(state.step>1){state.step--;render()}};stepView()}
function showFeedback(message,next){
 document.querySelectorAll('.option').forEach(b=>b.disabled=true);
 document.body.insertAdjacentHTML('beforeend',`<div class="feedback-overlay" role="status"><div class="feedback-card"><span class="feedback-check">✓</span><p>${message}</p><div class="feedback-timer"><i></i></div></div></div>`);
 const overlay=document.querySelector('.feedback-overlay:last-of-type'),bar=overlay.querySelector('.feedback-timer i'),started=performance.now();
 let advanced=false,timer,watchdog;
 const cleanup=()=>{clearTimeout(timer);clearInterval(watchdog);document.removeEventListener('visibilitychange',resume);window.removeEventListener('pageshow',resume);overlay.remove()};
 const advance=()=>{if(advanced)return;advanced=true;cleanup();next()};
 const resume=()=>{if(performance.now()-started>=1200)advance()};
 const frame=now=>{if(advanced)return;if(now-started>=1200)advance();else requestAnimationFrame(frame)};
 bar.addEventListener('animationend',advance,{once:true});
 document.addEventListener('visibilitychange',resume);
 window.addEventListener('pageshow',resume);
 timer=setTimeout(advance,1200);
 watchdog=setInterval(resume,250);
 requestAnimationFrame(frame)
}
function selectQ(step,value){const q=data[step];if(q.multi){let a=state.answers[q.key]||[];a=a.includes(value)?a.filter(x=>x!==value):a.length<q.max?[...a,value]:a;state.answers[q.key]=a;render();return}state.answers[q.key]=value;const o=q.opts.find(x=>x[0]===value);document.querySelector(`[data-v="${value}"]`)?.classList.add('chosen');track('EPOCHQuestionAnswer',{question:q.key,answer:value});showFeedback(o[2],()=>{state.step++;render()})}
function question(){const q=data[state.step],chosen=state.answers[q.key]||[];shell(`<div class="content question-content"><p class="eyebrow">YOUR EPOCH PREMIERE</p><h1>${q.title}</h1><div class="screen-visual" style="background-image:linear-gradient(0deg,rgba(5,5,6,.66),rgba(5,5,6,.03)),url('${art(state.step)}')"></div>${q.multi?'<p class="sub compact-sub">Choose up to 3.</p>':''}<div class="options ${state.step===10?'period-grid':''}">${q.opts.map(o=>`<button class="option ${(q.multi?chosen.includes(o[0]):chosen===o[0])?'chosen':''}" data-v="${o[0]}"><span>${o[1]}</span></button>`).join('')}</div>${q.multi?'<button class="primary compact-primary" id="continue" '+(!chosen.length?'disabled':'')+'>Continue</button>':''}</div>`);document.querySelectorAll('.option').forEach(b=>b.onclick=()=>selectQ(state.step,b.dataset.v));if(q.multi)document.getElementById('continue').onclick=()=>{track('EPOCHQuestionAnswer',{question:q.key,answer:chosen.join(',')});showFeedback(`${chosen.length} interests selected. We’re shaping your premiere.`,()=>{state.step++;render()})}}

function profile(){const motive=state.answers.motivation||'world',tone=state.answers.tone||'tense';const names={world:'World-Curious',smarter:'Knowledge-Driven',people:'People-Focused',conversation:'Story-Sharing',entertainment:'Entertainment-First',tense:'Suspense',epic:'Epic',emotional:'Human',investigative:'Investigative'};return `${names[motive]||'Curious'} · ${names[tone]||'Cinematic'}`}
function render(){if(state.step===1)return shell(`<div class="hero"><div><p class="eyebrow">PERSONALIZED CINEMATIC HISTORY</p><h1>Find the true stories you won’t stop watching.</h1><p>Tell us what grips you. We’ll build your premiere.</p><button class="primary" id="start">Build my premiere</button><small>About 2 minutes · No payment</small></div></div>`),document.getElementById('start').onclick=()=>{track('EPOCHQuizStart');state.step=2;render()};
if(state.step>=2&&state.step<=11)return question();
if(state.step===12){shell(`<div class="content processing"><p class="eyebrow">BUILDING YOUR PREMIERE</p><h1>Creating your personalized history profile…</h1><div class="screen-visual" style="background-image:linear-gradient(0deg,rgba(5,5,6,.68),rgba(5,5,6,.03)),url('${art(12)}')"></div><div class="analysis-bars"><div><span>Matching your interests</span><i></i></div><div><span>Balancing depth and time</span><i></i></div><div><span>Ranking your story worlds</span><i></i></div></div><p class="processing-status">Looking across your answers…</p></div>`);if(!state.processingStarted){state.processingStarted=true;setTimeout(()=>{state.step=13;render()},4800)}return}
if(state.step===13)return shell(`<div class="content email"><p class="eyebrow">YOUR PREMIERE IS READY</p><h1>Save your profile.</h1><div class="screen-visual email-visual" style="background-image:linear-gradient(0deg,rgba(5,5,6,.68),rgba(5,5,6,.03)),url('${art(13)}')"></div><p class="sub">Enter your email to reveal your recommendation and get launch access.</p><form id="lead" novalidate><label>Email<input type="email" name="email" required inputmode="email" autocomplete="email" placeholder="you@example.com"></label><label>Confirm email<input type="email" name="confirm_email" required inputmode="email" autocomplete="email" placeholder="Repeat your email"></label><input class="hp" name="website" tabindex="-1" autocomplete="off" aria-hidden="true"><p class="form-error" role="alert"></p><button class="primary">Reveal my premiere</button></form><small>No payment now. We’ll email you before launch.</small></div>`),document.getElementById('lead').onsubmit=submitLead;
if(state.step===14)return summary();
return destination()}
function validEmail(v){const email=v.trim().toLowerCase(),parts=email.split('@'),blocked=['example.com','test.com','fake.com','mailinator.com','tempmail.com'];return /^[^\s@]+@[^\s@]+\.[a-z]{2,}$/i.test(email)&&parts.length===2&&!blocked.includes(parts[1])&&!/^(gmai|gmial|hotnail|yaho)\./.test(parts[1])}
function submitLead(e){e.preventDefault();const f=e.target,email=f.email.value.trim().toLowerCase(),confirm=f.confirm_email.value.trim().toLowerCase(),err=f.querySelector('.form-error');err.textContent='';if(f.website.value)return;if(!validEmail(email)){err.textContent='Enter a valid email address (not a test or temporary address).';f.email.focus();return}if(email!==confirm){err.textContent='The email addresses do not match.';f.confirm_email.focus();return}state.email=email;const body=new URLSearchParams({"form-name":"epoch-quiz-leads",email:state.email,arm:state.arm,price:state.arm==='paywall'?state.price:'',profile:JSON.stringify(state.answers)});track('SubmitForm');track('Lead');fetch('/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body}).finally(()=>{state.step=14;render()})}
function summary(){const anchor=state.price==='14.99'?'19.99':'24.99';shell(`<div class="content summary"><p class="eyebrow">YOUR EPOCH PROFILE</p><h1>${profile()}</h1><p class="sub">You want human-scale pressure, clean context and consequences that keep opening doors.</p><div class="episode-cards"><article><div class="summary-visual" style="background-image:linear-gradient(0deg,rgba(5,5,6,.65),rgba(5,5,6,.05)),url('${art(14)}')"></div><b>EPISODE 1</b><h2>The Gate</h2><p>A diplomatic crisis closes in.</p><em>Ready to watch</em></article><article class="soon"><b>EPISODE 2</b><h2>444 Days</h2><p>The standoff changes everyone.</p><em>Coming soon</em></article><article class="soon"><b>EPISODE 3</b><h2>After the Headlines</h2><p>The consequences keep moving.</p><em>Coming soon</em></article></div>${state.arm==='paywall'?`<div class="offer"><p class="eyebrow">FOUNDING ACCESS</p><div class="price"><s>$${anchor}</s><strong>$${state.price}</strong><span>/month</span></div><ul><li>Episode 1 premiere</li><li>Founding price reserved</li><li>Email before any charge</li></ul><p>Price held for this session: <b id="timer">10:00</b></p><button class="primary" id="offerCta">Yes — reserve $${state.price}/month</button><button class="secondary" id="declineCta">Not at this price</button><small>No charge today. Your choice helps us test demand at this price.</small></div>`:`<button class="primary" id="offerCta">Start episode 1</button>`}</div>`);track('EPOCHRecommendationView');if(state.arm==='paywall'){track('InitiateCheckout',{currency:'USD',value:+state.price});track('PriceCellView',{currency:'USD',value:+state.price});tick()}document.getElementById('offerCta').onclick=()=>{if(state.arm==='paywall')track('EPOCHPriceIntent',{decision:'accept',currency:'USD',value:+state.price});state.step=15;render()};const decline=document.getElementById('declineCta');if(decline)decline.onclick=()=>{track('EPOCHPriceIntent',{decision:'decline',currency:'USD',value:+state.price});state.step=15;render()}}
function tick(){const el=document.getElementById('timer');if(!el)return;el.textContent=`${Math.floor(state.timer/60)}:${String(state.timer%60).padStart(2,'0')}`;if(state.timer-->0)setTimeout(tick,1000)}
function destination(){shell(`<div class="content player"><p class="eyebrow">${state.arm==='paywall'?'FOUNDING PRICE SAVED':'YOUR PREMIERE'}</p><h1>Episode 1: The Gate</h1><div class="video" style="background-image:linear-gradient(#0005,#0009),url('${art(15)}')"><div><b>EPISODE 1</b><span>Final approved episode video will be placed here.</span></div></div><button class="primary" id="complete">Complete episode 1</button><div class="coming"><article>Episode 2 <b>Coming soon</b></article><article>Episode 3 <b>Coming soon</b></article></div></div>`);document.getElementById('complete').onclick=()=>{track('series_complete',{available_episodes:1});app.querySelector('.content').innerHTML='<div class="done"><p class="eyebrow">PREMIERE COMPLETE</p><h1>Your next stories are coming soon.</h1><p>We’ll email you when the next episode is ready.</p></div>'}}
render();
})();
